#!/bin/bash
echo "🔍 Проверка доступности сервисов..."

echo ""
echo "📡 API Endpoints (снаружи Docker):"
echo "  • Health Check: http://localhost:8000/health"
echo "  • API Docs: http://localhost:8000/docs"
echo "  • Queue Status: http://localhost:8000/queue/status"
echo "  • Agents Status: http://localhost:8000/agents/status"

echo ""
echo "🗄️ База данных:"
echo "  • Внешний доступ: localhost:5432"
echo "  • Внутри Docker: postgres:5432"
echo "  • Проверка подключения:"
echo "    pg_isready -h localhost -p 5432 -U mjuser -d mjsystem"

echo ""
echo "🔴 Redis:"
echo "  • Внешний доступ: localhost:6379"
echo "  • Внутри Docker: redis:6379"
echo "  • Проверка подключения:"
echo "    redis-cli -h localhost -p 6379 ping"

echo ""
echo "🐳 Docker контейнеры:"
echo "  • Список: docker ps"
echo "  • Логи: docker-compose logs [service-name]"
echo "  • Сеть: docker network ls"

echo ""
echo "🧪 Тестовые команды:"
echo "# Проверить API"
echo "curl -f http://localhost:8000/health"
echo ""
echo "# Проверить PostgreSQL"
echo "nc -z localhost 5432 && echo 'PostgreSQL доступен' || echo 'PostgreSQL недоступен'"
echo ""
echo "# Проверить Redis"  
echo "nc -z localhost 6379 && echo 'Redis доступен' || echo 'Redis недоступен'"
echo ""
echo "# Проверить все контейнеры"
echo "docker-compose ps"